# Generated by Django 2.1.4 on 2018-12-30 18:10

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(default=time.time)),
                ('url', models.URLField(max_length=240, unique=True)),
                ('title', models.CharField(max_length=240, unique=True)),
                ('domain', models.CharField(max_length=120)),
                ('author', models.CharField(default='', max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('shares', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
