# Generated by Django 2.1.4 on 2018-12-30 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='timestamp',
            new_name='pub',
        ),
    ]
