# Generated by Django 2.1.4 on 2018-12-30 18:43

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181230_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub',
            field=models.FloatField(db_index=True, default=time.time),
        ),
        migrations.AlterField(
            model_name='article',
            name='shares',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
