# Generated by Django 2.1.4 on 2018-12-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181230_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='domain',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
