# Generated by Django 2.1.4 on 2019-05-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190428_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='reactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
