# Generated by Django 3.2.6 on 2021-09-09 20:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_article_paragraphs'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='downs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='article',
            name='ups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
