# Generated by Django 3.2.6 on 2021-09-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210909_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ups',
            new_name='pluses',
        ),
        migrations.RemoveField(
            model_name='article',
            name='downs',
        ),
    ]
