# Generated by Django 3.2.6 on 2021-09-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210909_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pluses',
            new_name='ips',
        ),
    ]
